#!/bin/bash

#SBATCH --time=40:00:00
#SBATCH --ntasks=15
#SBATCH -J routing

export PATH="/scratch/td7g11/julia/julia-1.0.1/bin/:${PATH}"

cd $HOME/sail_route.jl/development

current_time=$(date "+%Y.%m.%d-%H.%M.%S")
fname=multiple_simulations.$current_time

julia -p 15 polynesian/polynesian_simulations.jl $SLURM_ARRAY_TASK_ID
