#!/bin/bash

#SBATCH --time=40:00:00
#SBATCH --ntasks=20

export PATH="/scratch/td7g11/julia/julia-1.0.0/bin/:${PATH}"

cd $HOME/sail_route.jl/development

current_time=$(date "+%Y.%m.%d-%H.%M.%S")
fname=total_simulations.$current_time.txt

julia -p 20 < "parallized_total_analysis.jl" > $fname