#!/bin/bash

#SBATCH --time=20:00:00
#SBATCH --ntasks=10

export PATH="/scratch/td7g11/julia/julia-1.0.0/bin/:${PATH}"

cd $HOME/sail_route.jl/development

current_time=$(date "+%Y.%m.%d-%H.%M.%S")
fname=polynesian_output.$current_time.txt

julia -p 10 < "polynesian/example_simulations.jl" > $fname

