#!/bin/bash

#SBATCH --time=20:00:00
#SBATCH --nodes=1

export PATH="/scratch/td7g11/julia/julia-1.0.0/bin/:${PATH}"

cd $HOME/sail_route.jl/development

current_time=$(date "+%Y.%m.%d-%H.%M.%S")
fname=multiple_simulations.$current_time.txt

julia < "run_multiple_sims.jl" > $fname