# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
julia:
  - 1.0
notifications:
  email: false
before_script:
  - export PATH=$HOME/.local/bin:$PATH
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd())'
  - conda info -a
  - source activate $HOME/.julia/v0.6/Conda/deps/usr
  - conda install xarray pyproj shapely
  - conda install -c conda-forge esmpy basemap
  - pip install xesmf
  - julia -e 'Pkg.test("sail_route")'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("sail_route")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("sail_route")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
